jongwoo328/mytools

src/main.ts

- pnpm으로 패키지를 인스톨 하는 경우에서는 발생하지 않는 타입에러이나 npm, yarn을 통한 인스톨에서는 타입에러가 발생하고 있음

fix: 타입에러 보정

---

pages/converter/image-crop.vue

- remove timestamp query at vue-cropper in image-copper
close #90

remove timestamp query in image-cropper

---

pages/converter/image-crop.vue

change button position of image-crop

---

assets/scripts/textDiffWorker.js
components/viewer/TextDifferenceChecker.vue
nuxt.config.ts
pages/viewer/text-diff.vue
plugins/primevue.ts

fix freezing when pasting long text into textarea in text-diff
- add web worker to check text differences
- add some css to avoid overflowing text diffrence results
close #96

fix freezing text-diff (text-diff)

---

pages/converter/image-crop.vue

set image crossorigin anonymous
close #100 
thanks to @Woody-FE

fix not being able to save image crop result (image-crop)

---

components/formatter/JSONResultListItem.vue
plugins/vueJsonPretty.ts
utils/json.ts

add copy key button (formatter/json)

---

components/viewer/TextDifferenceChecker.vue

resolve layout issue with cancel button on mobile (text-diff)

---

nuxt.config.ts
pages/converter/color.vue
pages/converter/csv-to-json.vue
pages/converter/epoch.vue
pages/converter/image-crop.vue
pages/converter/image.vue
pages/converter/url.vue
pages/formatter/json.vue
pages/formatter/sql.vue
pages/viewer/html.vue
pages/viewer/text-diff.vue

add description for all pages

---

nuxt.config.ts
package.json
pages/converter/color.vue
pages/converter/csv-to-json.vue
pages/converter/epoch.vue
pages/converter/image-crop.vue
pages/converter/image.vue
pages/converter/url.vue
pages/formatter/json.vue
pages/formatter/sql.vue
pages/viewer/html.vue
pages/viewer/text-diff.vue
pnpm-lock.yaml

add jsonld

---

components/common/PageHeader.vue
components/common/ToolPageLayout.vue
components/converter/ImageInput.vue
pages/calculator/text-length.vue
pages/converter/color.vue
pages/converter/csv-to-json.vue
pages/converter/epoch.vue
pages/converter/image-crop.vue
pages/converter/image.vue
pages/converter/url.vue
pages/formatter/json.vue
pages/formatter/sql.vue
pages/index.vue
pages/viewer/html.vue
pages/viewer/text-diff.vue
utils/unit.ts

add text length calculator (calculator/text-length)

---

pages/calculator/text-length.vue

- add file formats
- application/json
- application/ld+json
- application/xml
- application/yaml
- application/x-sh
- application/xhtml+xml
- fix code to calculate file text length

add various file format and fix file text length logic (calculator/text-length)

---

components/formatter/JSONResultListItem.vue

add json minifier

---

pages/converter/image-crop.vue

fix to get image twice from server

---

pages/calculator/text-length.vue

add jsonld to text length calculator page (calculator/text-length)

---

components/common/LocaleDropdown.vue
layouts/default.vue
locales/en.json
locales/ko.json
pages/viewer/markdown.vue

and fix router view padding
close #135

fix(common) change language label

---

components/viewer/MarkdownRenderer.vue
locales/en.json
locales/ko.json
package.json
pages/viewer/markdown.vue
pnpm-lock.yaml

feat(viewer/markdown) add checkbox

---

pages/converter/image-crop.vue

fix(converter/image-crop): unintentional crop position movement

---

layouts/default.vue

fix(common): fix toast position

---

components/common/CommonToast.vue
components/common/LocaleDropdown.vue
layouts/default.vue

fix(common): fix toast bug and adjust ui alignments

---

components/common/PageHeading.vue
components/common/PageTitle.vue
components/common/ToolPageLayout.vue

adjust margin
